* Input for 02_process_cex.do
* Purpose: Label CEX data variables 

label var year "Year"
label var qtr "Quarter"
label var hhsize "Number of Members in CU"
*label var fincbt_x "Total amount of family income before taxes in the last 12 months (Collected data)"
label var amt_ssi "Amount of Supplemental Security Income from all sources received by all CU members in past 12 months (sum SSIX + SSIBX from MEMB file for all CU members)"
label var rentsubsidy "Are your housing costs lower because the Federal, State, or local government is paying part of the costs?"
label var nrooms "Number of rooms in CU living quarters, including finished living areas, excluding all baths"
label var amt_tanf "Amount received from public assistance or welfare including money received from job training grants such as Job Corps"
label var amt_snap "Value of all food stamps and electronic benefits received"
label var yq "Year Quarter"
label var age_youngest "Age of youngest member of CU for a given year"
*label var computer
label var equivrent "The maximum rental value of property (Sample Unit or second home) on today's market, including part of the property currently being used for business, farming, or being rented, for each CU in a given year"
label var lease_cost "The sum of amount paid in the first, second, and third month of the reference period for the vehicle lease"
label var lease_cost_pred "Predicted vehicle lease cost"
label var owns_used "CU owns used vehicle in a given year"
label var owns_new "CU owns new vehicle in a given year"
label var n_adults "Number of adults in CU in a given year"
label var n_children "Number of children in CU in a given year"
label var n_people "Number of people in CU in a given year"
*label var perid "Person-ID"
label var educ "Education of reference person"
label var disabled "Reference person has a disability"
label var unemploy "Reference person is unemployed"
label var nilf "Reference person is not in labor force"
label var employ "Reference person is employed"
label var cpi "Consumer Price Index"
*label var housing_exp "Shelter experience this and last quarter"
label var wsav_nom "Total value of liquid cash and other investments/assets"
label var single_parent "Single parent in CU"
label var has_child "CU has children"
label var food_at_home "CU access to food"
label var gasoline "CU access to gasoline"
label var utility_exp "CU access to utilities"
label var owns_car "CU owns car"
label var central_ac "CU has access to central AC"
label var owns_home "CU owns a home"
label var married "Reference person is married"
label var health_exp "CU access to health insurance"
*label var amt_snap1 "SNAP value"
*label var amt_snap2 "SNAP value"
*label var amt_snap3 "SNAP value"
*label var amt_snap4 "SNAP value"
*label var amt_snap5 "SNAP value"
label var snap "Has access to SNAP"
label var ssi "Has access to supplemental security income"
label var housing_assistance "Uses to public housing or housing subsidy"
label var tanf "Has access to TANF"
label var eqscale "Equivalence scale"
label var anychild "CU has at least one child"
label var cons_a "Total consumption value"
label var cons_adj "Total inflation-adjusted consumption value"
label var rk_cons "Rank of consumption value by year-quarter"
label var earnings_qx "Total amount of family earnings income before taxes"
*label var spmlunch_amt_hh ""
label var amt_rentsubsidy "Amount of rent subsidy received (inflation and household size adjusted)"
label var amt_publichousing "Value of public housing received (inflation and household size adjusted)"
label var amt_medicaid "Value of medicaid received (inflation and household size adjusted)"
*label var wcar_nom "Nomial value of owned car"
*label var woth_nom ""
*label var whome_nom
*label var yr_us
*label var qualified_imm ""
*label var citizen
*label var head
*label var spouse
label var famid "Sequence number which uniquely identifies families"
label var eligsim_snap "Simulated eligibility for SNAP"
label var eligsim_housing_assistance "Simulated eligibility for housing assistance"
label var eligsim_ssi "Simulated eligibility for social security income"
label var eligsim_medicaid "Simulated eligibility for medicaid"
label var eligsim_tanf "Simulated eligibility for TANF"
label var age "What is the member's age?"
label var aliothx "During the past 12 months, what was the total amount of income from regular contributions from alimony and other sources, such as from persons outside the CU received by ALL CU members?"
label var aliothxm "During the past 12 months, what was the total amount of income from regular contributions from alimony and other sources such as from persons outside the CU received by ALL CU members?"
label var chdothx "Total amount received by all CU members in last 12 months for other child support"
label var chdothxm "Total amount received by all CU members in last 12 months for other child support, mean of imputation iterations."
label var compensm "Amount received from workmen's compensation and veteran's payments including education, mean of imputation iterations."
label var compensx "Amount received from workmen's compensation and veteran's payments including education"
label var cuid "CU sequence number which uniquely identifies CUs (Digits 1-7 of NEWID)"
label var earnincx "Total amount of family earnings income before taxes"
label var educ_ref "Education of reference person"
label var educa2 "What is the highest level of school the spouse has completed or the highest degree the member has received?"
label var etotacx4 "Adjusted total outlays last quarter, sum of outlays from all major expenditure categories."
label var etotalc "Total outlays this quarter, sum of outlays from all major expenditure categories."
label var etotalp "Total outlays last quarter, sum of outlays from all major expenditure categories."
label var etotapx4 "Adjusted total outlays last quarter, sum of outlays from all major expenditure categories."
label var ffrmincm "Total amount of income or loss received from own farm, mean of imputation iterations."
label var ffrmincx "Total amount of income or loss received from own farm"
label var fincatax "Total amount of family income after taxes in the last 12 months (Collected data)"
label var fincatxm "Total amount of family income after taxes in the last 12 months (Imputed or collected data)"
label var fincbtax "Total amount of family income before taxes in the last 12 months (Collected data)"
label var fincbtxm "Total amount of family income before taxes (Imputed or collected data)"
label var finincx "Amount of regular income earned from dividends, royalties, estates, or trusts"
label var finincxm "Amount of regular income received from dividends, mean of imputation iterations."
label var finlwt21 "Calibration final weight for the full sample"
label var fnonfrmm "Total amount of income received from non-farm business, partnership or professional practice by family grouping, mean of imputation iterations"
label var fnonfrmx "Total amount of income received from non-farm business, partnership or professional practice by family grouping."
label var foodsmpi "Indicator/descriptor variable for income imputation."
label var foodsmpm "Total amount of income received from food stamps and electronic benefits, mean of imputation iterations."
label var frretirm "Total amount of received from Social Security benefits and Railroad benefit checks prior to deductions for medical insurance and Medicare, mean of imputation iterations"
label var frretirx "Total amount received from Social Security benefits and Railroad Benefit checks prior to deductions for medical insurance and Medicare"
label var fs_mthi "year on which stamps were received during the month) - first"
label var fs_mthi "In how many of the past 12 months were food stamps or EBTs received?"
label var fsalarym "Total amount of income received from salary or wages before deduction by family grouping, mean of imputation iterations"
label var fsalaryx "Total amount of income received from salary or wages before deduction by family grouping"
label var fsmpfrmx "Family level summation for new variable SEMPFRMX and SMPFRMBX"
label var fsmpfrmx "Total income received from self-employment income before deduction by family grouping"
label var fsmpfrxm "Total amount of income received from self-employment income by family grouping, mean of imputation iterations"
label var fssixm "Total amount received in supplemental security income checks combined, mean of imputation iterations"
label var hhid "Identifier for household with more than one CU. Household with only one CU will be set to missing."
label var hhid "Identifier for household with more than one CU. Household with only one CU will be set to missing."
label var hhipdlib "Policy Number"
label var hhmcrcov "Number of CU members covered by Medicare"
label var hisp_ref "Hispanic origin of reference person"
label var hisp2 "Hispanic origin of spouse"
label var hispanic "Country of Hispanic Origin"
label var horigin "Are you Spanish, Hispanic, or Latino?"
label var horref1 "Hispanic Origin of the Reference Person"
label var horref2 "Hispanic Origin of the spouse"
label var inc_hrs1 "Number of hours usually worked per week by reference person"
label var inc_hrs2 "Number of hours usually worked per week by spouse"
label var inc_rank "Weighted cumulative percent ranking based on total current income before taxes"
label var inc_rnkm "Weighted cumulative percent ranking based on total current income, based on mean of imputation iterations"
label var inclosam "Amount of net income or loss received from roomers or boarders, mean of imputation iterations."
label var inclosbm "Amount of net income or loss received from payments from other rental units, mean of imputation iterations."
label var inclossa "Amount of net income or loss received from roomers or boarders"
label var inclossb "Amount of net income or loss received from payments from other rental properties"
label var int_phon "Do you or anyone in this household have high speed internet access through a smartphone and a data plan?"
label var intearnm "Amount received as interest on savings accounts or bonds, mean of imputation iterations."
label var intearnx "Amount earned as interest on savings accounts or bonds"
label var interi "Interview number"
label var intrdvbx "Median of Bracket Range"
label var intrdvx "Amount of income received from interest and dividends"
label var intrdvxm "Amount of income received from interest and dividends, mean of the iterations"
label var irax "In the past 12 months what is the total amount put into retirement accounts, such as 401(k)s, IRAs, and Thrift Savings Plans that you own?"
label var irax "As of today, what is the total value of all retirement accounts, such as 401(k)s, IRAs, and Thrift Savings Plans that you own?"
label var jfs_amtm "Annual value of food stamps, mean of imputation iterations."
label var jmdcdqvx "Quarterly expenditures on Medicaid premiums"
label var liquidx "As of today, what is the total value of all checking, savings, money market accounts, and certificated of deposit or CDs you have?"
label var mdcdcov "Number of CU members covered by Medicaid"
label var mdcdprmx "What is the monthly premium for this Medicaid plan?"
label var medicaid "Are you covered by Medicaid?"
label var medprem "Do you pay a premium for your Medicaid plan?"
label var netrentm "Amount of income received from net rental income or loss, mean of the iterations"
label var netrentx "What was the amount of net rental income or loss?"
label var netrntbx "Median of Bracket Range"
label var newid "Public use microdata identifier"
label var newid "Public use microdata identifier"
label var othastx "As of today, what is the total value of these other financial assets?"
label var othmed "Are you, or any member, covered by a plan such as VA Medical, CHAMPVA, STCHIP, or Indian Health Service (IHS)?"
label var othplan "Are you or any member of your CU covered by any plan other than Medicare or Medicaid which provides free health care such as TRICARE, CHAMPUS or military health care?"
label var othregbx "Median of Bracket Range"
label var othregx "Amount of income received from any other source such as Veteran's Administration (VA) payments, unemployment compensation, child support, or alimony"
label var othregxm "Amount of income received from any other source such as Veteran's Administration (VA) payments, unemployment compensation, child support, or alimony, mean of the iterations"
label var othrincm "Amount received in other money income including money received from care of foster children, mean of imputation iterations."
label var othrincx "Amount received in other money income including money received from care of foster children, cash scholarships and fellowships, or stipends not based on working"
label var otrincbx "Median of bracket range"
label var pensionm "Amount received from pensions or annuities from private companies, military, or government, mean of imputation iterations."
label var pensionm "Amount received from pensions or annuities from private companies, mean of imputation iterations."
label var pensionx "Amount received from pensions or annuities from private companies, military, or government"
label var perinscq "heading prior to this list of variables. Personal insurance and pensions this quarter"
label var perinspq "heading prior to this list of variables. Personal insurance and pensions last quarter"
label var povlevcy "Poverty threshold for this CU in the current year"
label var publhous "Is this house in a public housing project, that is, is it owned by a local housing authority or other local public agency?"
label var race "Race of Member"
label var race2 "Race of spouse"
label var ref_race "Race of reference person"
label var respstat "Completeness of income response status by code"
label var retsrvbx "Median of Bracket Range"
label var retsurvm "Amount of income received from retirement, survivor, or disability pensions, mean of the iterations"
label var retsurvx "What was the amount received in retirement, survivor, or disability pensions during the past 12 months."
label var retsurvx "What was the amount received in retirement, survivor, or disability pensions during the past 12 months."
label var rntxrpcq "Rent excluding rent as pay this quarter"
label var rntxrppq "Rent excluding rent as pay last quarter"
label var royestbx "Median of Bracket Range"
label var royestx "Amount of income received from royalty income or income from estates and trusts"
label var royestxm "Amount of income received from royalty income or income from estates and trusts, mean of the iterations"
label var savacctx "Total balance or market value (including interest earned) CU had in savings accounts in banks, savings and loans, credit unions, etc., as of the last day of previous month"
label var secestx "Estimated market value of all stocks, bonds, mutual funds, and other such securities held by CU on the last day of the previous month"
label var interi "Interview Number"
label var sex "Sex of Member"
label var sheltcq "Shelter this quarter"
label var sheltpq "Shelter last quarter"
label var ssibx "Median of bracket range"
label var ssix "Amount received in supplemental security income checks combined"
label var ssixm "Amount received in supplemental security income checks combined, mean of imputation iterations."
label var state "Federal information processing standard state code"
label var state "The 2010 Federal information processing standard state code"
label var stockx "As of today, what is the total value of all directly-held stocks, bonds, and mutual funds?"
label var totexpcq "Total expenditures this quarter"
label var totexppq "Total expenditures last quarter"
label var unemplx "Amount received from unemployment compensation"
label var unemplxm "Amount received from unemployment compensation, mean of imputation iterations."
label var vehnewu "Was it new or used when acquired?"
label var welfareb "Range that best reflects the total amount of income from cash assistance from state or local government welfare programs during the last 12 months"
label var whlfyrx "What was the total surrender value of these policies one year ago today?"
